on:
  push:
    branches: [master]
  pull_request:
name: build
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: flatpak/flatpak-github-actions/flatpak-builder@92ae9851ad316786193b1fd3f40c4b51eb5cb101 # v6.6
      with:
        bundle: supermicro.IPMIView
        manifest-path: com.supermicro.IPMIView.yml
        cache-key: flatpak-builder-${{ github.sha }}
