on:
  push:
    branches: [master]
  pull_request:
name: build
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - uses: flatpak/flatpak-github-actions/flatpak-builder@10a3c29f0162516f0f68006be14c92f34bd4fa6c # v6.5
      with:
        bundle: supermicro.IPMIView
        manifest-path: com.supermicro.IPMIView.yml
        cache-key: flatpak-builder-${{ github.sha }}
